### ISSUE TITLE
[Object] ES6: Destructuring Objects IV

### ISSUE THREAD

**Issue by DimaKacer** [SovanMarat/JS-Front-end-Lab#36]
const obj =  { first: "James", last: "Baker", alias: "JB"  }

var { first = "John", last = "Doe", alias } = obj

console.log(nickname) // outputs nickname is not defined
There may be times where we would like the property name to be different from the object property names we receive and also give those new property names a default value.

**Comment by SovanMarat** [comment]
Не могу понять условие задания. На входе объект с именем и фам и по первым буквам мы добавляем в объект alias?

**Comment by DimaKacer** [comment]
Initial desc:
There may be times where we would like the property name to be different from the object property names we receive and also give those new property names a default value.

Translate:
Могут быть случаи, когда нам нужно, чтобы имя свойства отличалось от имен свойств объекта, которые мы получаем, а также присвоить этим новым именам свойств значение по умолчанию.

А теперь ближе к задаче:
1) Тема - Диструкторизация
2) Есть исходный объект - нужно найти его из двух  строк предоставленных выше в условии
3) соответственно в другой инструкции, вы диструкторизируем проперти объекта
4) Вплотную подошли к задаче) - нам нужно первое - чтобы имя свойства (одно из) отличалось от имен свойств исходного объекта (нужно сравнить два объекта, на предмет соответстия имени пропертей, и если есть разница в пропертях нужно реализовать фичу переименования проперти в желаемое имя, для дальнейшего удобства / чтобы код заработал....
второе - присвоить значение поумолчанию, для нового имени

Надеюсь так понятнее...
