### ISSUE TITLE
Разбить Лендинг пейдж по компонентам

### ISSUE THREAD

**Issue by DimaKacer** [SovanMarat/JS-Front-end-Lab#64]
их должно получиться не меньше 5ти штук
![image](https://user-images.githubusercontent.com/10163185/123062541-4b708880-d415-11eb-85e5-8a2244ae1e5f.png)

**Comment by SovanMarat** [comment]
5 ый блок (с раскрывающимся списком) в первом варианте на HTML ты исключал, сейчас добавлять его?

**Comment by DimaKacer** [comment]
![image](https://user-images.githubusercontent.com/10163185/126165993-4e4d3307-f2b7-4ae5-a5ec-ad8b62ac2d27.png)
